name 'localmake'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures localmake'
long_description 'Installs/Configures localmake'
version '0.1.0'
